---
title: "2024 General Election Forcasting Model"
subtitle: "POLSCI 239 - Assignment Four"
author: "Jack Regan"
format: pdf
editor: visual
---

```{r}
#| lable: load-libraries
#| message: false

library(tidyverse)
library(ggplot2)
library(readr)
library(janitor)
library(stats)
```
# Data Set

The data for this model is borrowed from ABC's 538 general election state polling dataset. The guidelines for polls selection can be reviewed on 538's webpage, here: https://abcnews.go.com/538/polling-averages-work/story?id=109364028.
```{r}
#| label: read-polling-data
polling_data <- read_csv("data/president_polls.csv", show_col_types = FALSE)
glimpse(polling_data)
```
```{r}
#| lable: select-columns-and-filter
toss_up_states <- c("Michigan", "Nevada", 
      "Arizona", "New Mexico", 
      "Wisconsin", "Pennsylvania", 
      "North Carolina", "Georgia")

polling_data <- polling_data |>
  select(
    poll_id,
    state,
    start_date,
    end_date,
    pollster_rating_id, 
    numeric_grade, 
    sample_size, 
    candidate_name, pct
  ) |>
  filter(candidate_name == "Kamala Harris") |>
  filter(state %in% toss_up_states)
```

```{r}
#| label: generate-state-specific-datasets
mi_polling_data <- polling_data |>
  filter(state == "Michigan")
nv_polling_data <- polling_data |>
  filter(state == "Nevada")
ar_polling_data <- polling_data |>
  filter(state == "Arizona")
nm_polling_data <- polling_data |>
  filter(state == "New Mexico")
wi_polling_data <- polling_data |>
  filter(state == "Wisconsin")
pa_polling_data <- polling_data |>
  filter(state == "Pennsylvania")
nc_polling_data <- polling_data |>
  filter(state == "North Carolina")
ga_polling_data <- polling_data |>
  filter(state == "Georgia")
```

```{r}
#| label: calculate-margin-by-state
polling_data |>
  group_by(state) |>
  summarize(
    count = n(),
    count_not_na = count - sum(is.na(numeric_grade)),
    mean_pct = mean(pct)
  )
```
